version = 0.1
[default.deploy.parameters]
stack_name = "auto-transcriber-1"
resolve_s3 = true
s3_prefix = "auto-transcriber-1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputBucketName=\"mable-audio-files\""
image_repositories = []
